// Mock data for destinations
export const mockDestinations = [
  {
    id: '1',
    name: 'Goa',
    country: 'India',
    category: 'Beach',
    image: 'https://images.unsplash.com/photo-1512453475620-e0e99bba2870?w=800&q=80',
    rating: 4.5,
    reviews: 1250,
    estimatedBudget: 25000,
    weather: 'Tropical',
    bestSeason: 'October - May',
    description: 'Beautiful beaches and vibrant nightlife',
    attractions: ['Baga Beach', 'Fort Aguada', 'Dudhsagar Waterfall'],
    safetyRating: 4.2,
    visaRequired: false,
  },
  {
    id: '2',
    name: 'Bali',
    country: 'Indonesia',
    category: 'Beach',
    image: 'https://images.unsplash.com/photo-1549144611-f82f6405c8ad?w=800&q=80',
    rating: 4.7,
    reviews: 3500,
    estimatedBudget: 35000,
    weather: 'Tropical',
    bestSeason: 'April - October',
    description: 'Exotic beaches and rich culture',
    attractions: ['Ubud Monkey Forest', 'Tanah Lot Temple', 'Rice Terraces'],
    safetyRating: 4.4,
    visaRequired: true,
  },
  {
    id: '3',
    name: 'Himalayan Mountains',
    country: 'India',
    category: 'Mountains',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    rating: 4.6,
    reviews: 890,
    estimatedBudget: 30000,
    weather: 'Cold',
    bestSeason: 'May - September',
    description: 'Breathtaking mountain views and adventure',
    attractions: ['Manali', 'Shimla', 'Rohtang Pass'],
    safetyRating: 4.5,
    visaRequired: false,
  },
  {
    id: '4',
    name: 'Venice',
    country: 'Italy',
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&q=80',
    rating: 4.8,
    reviews: 5200,
    estimatedBudget: 85000,
    weather: 'Mild',
    bestSeason: 'April - October',
    description: 'Historic canals and Renaissance art',
    attractions: ['St. Marks Basilica', 'Grand Canal', 'Rialto Bridge'],
    safetyRating: 4.6,
    visaRequired: true,
  },
  {
    id: '5',
    name: 'Taj Mahal',
    country: 'India',
    category: 'Religious',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    rating: 4.9,
    reviews: 8900,
    estimatedBudget: 15000,
    weather: 'Moderate',
    bestSeason: 'October - March',
    description: 'Monument of love and architectural marvel',
    attractions: ['Taj Mahal', 'Agra Fort', 'Mehtab Bagh'],
    safetyRating: 4.3,
    visaRequired: false,
  },
  {
    id: '6',
    name: 'Maldives',
    country: 'Maldives',
    category: 'Honeymoon',
    image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&q=80',
    rating: 4.9,
    reviews: 4100,
    estimatedBudget: 120000,
    weather: 'Tropical',
    bestSeason: 'November - April',
    description: 'Overwater bungalows and crystal clear water',
    attractions: ['Coral Reefs', 'Snorkeling', 'Water Sports'],
    safetyRating: 4.8,
    visaRequired: false,
  },
]

export const mockHotels = [
  {
    id: 'h1',
    name: 'The Taj Hotel',
    location: 'Agra, India',
    rating: 4.7,
    reviews: 2400,
    pricePerNight: 5500,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    amenities: ['WiFi', 'AC', 'Pool', 'Gym', 'Restaurant'],
    roomTypes: [
      { id: 'r1', name: 'Standard', price: 5500, capacity: 2, amenities: ['AC', 'WiFi'], image: '' },
      {
        id: 'r2',
        name: 'Deluxe',
        price: 8500,
        capacity: 4,
        amenities: ['AC', 'WiFi', 'Balcony'],
        image: '',
      },
    ],
    description: 'Luxury hotel with Taj Mahal views',
    coordinates: { lat: 27.1751, lng: 78.0421 },
  },
  {
    id: 'h2',
    name: 'Sunset Beach Resort',
    location: 'Goa, India',
    rating: 4.5,
    reviews: 1890,
    pricePerNight: 3500,
    image: 'https://images.unsplash.com/photo-1582719470997-c3babe6e588d?w=800&q=80',
    amenities: ['Beach Access', 'WiFi', 'Pool', 'Spa', 'Restaurant'],
    roomTypes: [
      { id: 'r3', name: 'Beach View', price: 3500, capacity: 2, amenities: ['AC', 'Beach View'], image: '' },
      {
        id: 'r4',
        name: 'Suite',
        price: 6500,
        capacity: 4,
        amenities: ['AC', 'Jacuzzi', 'Beach Access'],
        image: '',
      },
    ],
    description: 'Beachfront resort with water sports',
    coordinates: { lat: 15.2993, lng: 73.8243 },
  },
  {
    id: 'h3',
    name: 'Mountain Peak Lodge',
    location: 'Manali, India',
    rating: 4.6,
    reviews: 1200,
    pricePerNight: 4200,
    image: 'https://images.unsplash.com/photo-1584622614875-2953066ef9d5?w=800&q=80',
    amenities: ['Mountain View', 'Fireplace', 'Restaurant', 'Hiking Tours'],
    roomTypes: [
      { id: 'r5', name: 'Cozy Room', price: 4200, capacity: 2, amenities: ['Heater', 'View'], image: '' },
      {
        id: 'r6',
        name: 'Suite',
        price: 7200,
        capacity: 4,
        amenities: ['Fireplace', 'Balcony'],
        image: '',
      },
    ],
    description: 'Cozy mountain lodge with adventure activities',
    coordinates: { lat: 32.2396, lng: 77.1887 },
  },
]

export const mockActivities = [
  {
    id: 'a1',
    name: 'Taj Mahal Sunrise Tour',
    cost: 1500,
    duration: 3,
    location: 'Agra',
    type: 'Sightseeing',
    description: 'Witness the magical sunrise at Taj Mahal',
  },
  {
    id: 'a2',
    name: 'Scuba Diving',
    cost: 3500,
    duration: 4,
    location: 'Goa',
    type: 'Water Sports',
    description: 'Explore coral reefs and marine life',
  },
  {
    id: 'a3',
    name: 'Hiking to Waterfall',
    cost: 1200,
    duration: 5,
    location: 'Manali',
    type: 'Adventure',
    description: 'Trek to pristine mountain waterfall',
  },
  {
    id: 'a4',
    name: 'Cooking Class',
    cost: 800,
    duration: 2,
    location: 'Goa',
    type: 'Cultural',
    description: 'Learn to cook traditional Indian cuisine',
  },
  {
    id: 'a5',
    name: 'Yoga and Meditation',
    cost: 500,
    duration: 1.5,
    location: 'Bali',
    type: 'Wellness',
    description: 'Rejuvenate with yoga and meditation session',
  },
]

export const budgetData = {
  economy: {
    flightCost: 15000,
    hotelCost: 2500,
    foodCost: 800,
    transportCost: 500,
    activitiesCost: 2000,
  },
  luxury: {
    flightCost: 50000,
    hotelCost: 10000,
    foodCost: 3000,
    transportCost: 2000,
    activitiesCost: 8000,
  },
}
